version: '3.8'
services:
  redis:
    container_name: redis-db
    image: redis
  backend:
    container_name: backend
    environment:
      - REDIS_HOST=redis
    build: ./backend
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - redis
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - backend
