server:
  port: 8080
app:
  timeToLive: -1 # '-1' for turning expiry off; otherwise, should be at least '1' (minute)
db:
  type: sql # ['sql', 'redis', 'in-memory']  // redis type is not yet implemented fully
  redis:
    port: 6379
  sequelize:
    user: 'root'
    password: 'password' # INSERT PASSWORD HERE
    db: 'clinic'
    dialect: 'mysql'
