server:
  port: 8080
app:
  timeToLive: -1 # '-1' for turning expiry off; otherwise, should be at least '1' (minute)
db-type:
  queue: redis # ['sql', 'redis', 'in-memory']
  patients/resolutions: sql # ['sql', 'redis', 'in-memory']
redis:
  port: 6379
sequelize:
  user: 'root'
  password: 'password' # INSERT PASSWORD HERE
  db: 'clinic'
  dialect: 'mysql'
