version: '3.8'
services:
  redis:
    container_name: redis
    image: redis
  mysql:
    container_name: mysql
    image: mysql:latest
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password # INSERT PASSWORD
      MYSQL_DATABASE: clinic
      MYSQL_USER: root
      MYSQL_PASSWORD: password # INSERT PASSWORD
    ports:
      - '3307:3306'
  backend:
    container_name: backend
    environment:
      - MYSQL_HOSTNAME=mysql
      - REDIS_HOST=redis
    build: ./backend
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - redis
      - mysql
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - backend
